---
# handlers file for goozbach.pulp_server
- name: Restart Apache service
  service:
    name: httpd
    state: restarted

- name: Restart Pulp workers service
  service:
    name: pulp_workers
    state: restarted

- name: Restart Pulp celerybeat service
  service:
    name: pulp_celerybeat
    state: restarted

- name: Restart Pulp resource manager service
  service:
    name: pulp_resource_manager
    state: restarted
