Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"

  config.vm.define "web" do |web|
    web.vm.hostname = "web.example.com"
    web.vm.network "private_network", ip: "10.232.0.20"
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db.example.com"
    db.vm.network "private_network", ip: "10.232.0.21"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end
end
