Vagrant.configure(2) do |config|

  config.vm.define "web" do |web|
    web.vm.box = "bento/centos-7.2"
    web.vm.hostname = "web.example.com"
    web.vm.network "private_network", ip: "192.168.21.20"
  end

  config.vm.define "mydocker" do |container|
    container.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "host/Vagrantfile"
      d.image = "nginx:latest"
      d.name = "mydocker"
    end
  end

end
