---
# tasks file for goozbach.pulp_consumer
- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: install pulp consumer packages
  package: name={{ item }} state=installed
  with_items: "{{ pulp_consumer_packages }}"

- name: template pulp consumer files
  template: src={{ item.source }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items: "{{ pulp_consumer_templates }}"
