---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- include: pulp_server.yaml
  when: pulp_install_server

- include: pulp_patch.yaml
  when: pulp_patch

- include: pulp_admin.yaml
  when: pulp_install_admin

- include: pulp_consumer.yaml
  when: pulp_install_consumer
