---
- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: fetch rhel pulp repo file
  get_url: url="{{ pulp_repo_url }}" dest="/etc/yum.repos.d/rhel-pulp.repo" owner=root group=root mode=0644

- name: install master packages
  yum: name={{ item }} state=installed disablerepo='BH*'
  with_items: "{{ pulp_server_packages }}"
  notify:
    - Restart Apache service
    - Restart Pulp workers service
    - Restart Pulp celerybeat service
    - Restart Pulp resource manager service

- name: template master files
  template: src={{ item.source }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items: "{{ master_templates }}"
  notify:
    - Restart Apache service
    - Restart Pulp workers service
    - Restart Pulp celerybeat service
    - Restart Pulp resource manager service

- name: start and enable services
  service: name={{ item }} state=started enabled=True
  with_items: "{{ master_services }}"

- name: dry run of managedb
  command: /usr/bin/pulp-manage-db --dry-run
  become: true
  become_user: apache
  become_method: sudo
  register: managedb
  changed_when: False
  ignore_errors: True

- name: re-run managedb if needed
  command: /usr/bin/pulp-manage-db
  become: true
  become_user: apache
  become_method: sudo
  when: managedb.rc == 1
  notify:
    - Restart Apache service
    - Restart Pulp workers service
    - Restart Pulp celerybeat service
    - Restart Pulp resource manager service

- name: open up api port
  firewalld: port={{ pulp_server_api_port }} permanent=True state=enabled immediate=True
  when: "{{ ansible_distribution_major_version|int }} >= 7 and {{ pulp_server_open_api_port }}"

- name: open up http port
  firewalld: port="80/tcp" permanent=True state=enabled immediate=True
  when: "{{ ansible_distribution_major_version|int }} >= 7 and {{ pulp_server_open_api_port }}"
